jobs:
  build:
    docker:
    - image: cimg/base:stable
    steps:
    - run: which docker
    - run: docker -v
    - setup_remote_docker
    - run: docker network ls -f name=testing_network -q
    - run:
        name: Build a really docker image
        command: |
          existing_networks=$(docker network ls -f name=testing_network -q)
          echo $existing_networks
          echo "start conditional"
          if [ -z "$existing_networks" ]; then
            docker network create -d bridge testing_network
          else
            echo OK
          fi
          echo "end"
